version: '2.0'
services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: service:database
  database:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: root
      POSTGRES_DB: postgres
volumes:
  postgres-data:
